services:
  db:
    restart: always
    image: postgres:latest
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5438:5432

volumes:
  postgres_data:
